### ISSUE TITLE
ValueError: No such layer: activation

### ISSUE THREAD

**Issue by Ashish1997** [anish9/Tensorflow2.0-face-segmentation#1]
In keras.application.ResNet50 there is no layer named "activation" or "activation_2" .. and so on used in UNET(classes) function.

While running I got this error which is obvious.
Help me to fix this.

a1 = base_model.get_layer("activation").output  
  File "/home/artivatic/Desktop/Health claims/Tensorflow2.0-face-segmentation/tf_2.0_venv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py", line 539, in get_layer
    raise ValueError('No such layer: ' + name)
ValueError: No such layer: activation

**Comment by anish9** [comment]
@Ashish1997  let me know your hardware and installation config details
